#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr &
$HOME/.fehbg &
polybar &
picom &
nm-applet &
conky &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gvim desktop='^2' state=fullscreen follow=on
bspc rule -a librewolf desktop='^3' follow=on
bspc rule -a Chromium desktop='^3'
bspc rule -a vlc desktop='^5' follow=on state=fullscreen
bspc rule -a mpv desktop='^5'
bspc rule -a qBittorrent desktop='^6'
bspc rule -a Epdfview state=fullscreen follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

