import = ["/home/ananyo/.config/alacritty/colorschemes.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 18

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Normal"

[window]
opacity = 0.8
